// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce_flutter/hive_flutter.dart';
import 'package:dump/models/hive_products.dart';
import 'package:dump/screens/products.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ProductAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ProductAdapter());
  }
}
